### PR TITLE
Feature exception2

### PR DESCRIPTION
**Pull request by chryswoods**
The recent merge of feature_exception into devel actually DELETED all of the changes in feature_exception. It looks like the merge commit only pulled in the change from the first commit to feature_exception, then the rest was removed.

(I recommend using "git pull origin branch" within a feature branch to pull in changes from other feature branches if merging multiple branches together, e.g.

```
git checkout feature_branch1
git pull origin feature_branch2
# fix any conflicts
git pull origin feature_branch3
# fix any conflicts
# check no other changes on devel
git pull origin devel
# fix any conflicts
git push
```

then complete the pull request of feature_branch1 as it will merge in and close all of the other feature branches)

This couldn't be reverted, so I have manually restored feature_exception, then created feature_exception2 from devel, then copied across all of the changed files from feature_exception to feature_exception2. I then regenerated all of the Python wrappers.

I believe that all of the other merges are still preserved - the new mol/test_matcher.py test still exists and passes.

@lohedges - please check that I haven't trashed your changes.

### CODE REVIEW

**Comment by lohedges** [comment]
Thanks, I'll check on Monday but can't see any issue if the `AtomCoordMatcher` test is still there and passes. I'm really puzzled as to what went wrong since all feature and fix branches were fully up to date before merging. (I actually used a fresh clone of the repo and pulled each branch as in your example.) I'll certainly double check when merging next time.

**Comment by lohedges** [comment]
The weird thing is that I see _all_ of the commits from the merged/closed `feature_exception` branch in `devel`?

**Comment by chryswoods** [comment]
It was really weird - the "fix commit" I added which just added a single blank line to lj1264parameter.cpp almost broke GitHub. It couldn't render the PR and said that it would have to be manually resolved (against a file that didn't exist).

I think it was some weird git bug.

**Comment by lohedges** [comment]
Looks good. All of the other edits are still there :+1:

**Pull request merged**
