### PR TITLE
Fix analyse_freenrg TI for unequal sample sizes

### PR DESCRIPTION
**Pull request by fjclark**
Several arrays were initialised with zeros according to the maximum sample size. When simulations at different lambda windows were run for unequal lengths of time, this meant that the end of most arrays consisted of 0s. Taking the mean of these arrays produced means which were erroneously close to 0, producing highly incorrect TI estimates.

To avoid this, I've replaced arrays initialised with 0s with arrays initialised with nans, and used the functions `nanmean` and `nanstd` to ignore the nans. I have tested on previous output to confirm that the MBAR result is identical to previously, while the TI results show dramatic changes.

# Is this pull request to fix a bug, or to introduce new functionality?

This pull request fixes issue #85.

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): y
* I confirm that I have added a changelog entry to the changelog (we will add a link to this PR as part of the review): y
* I confirm that I have permission to release this code under the GPL3 license: y

## Suggested reviewers:
@chryswoods, @lohedges

## Any additional context of information?

Many of the changes are due to auto-formatting with black.

### CODE REVIEW

**Comment by chryswoods** [comment]
Looks good - I think the CI failure is to do with tags I broke a while back. I will pull this into the PR for 2023.3.1 and will build and test there. This should also mean that this fix will make it for 2023.3.1 ;-)

**Comment by fjclark** [comment]
Perfect, thanks!

**Comment by lohedges** [comment]
>  I think the CI failure is to do with tags I broke a while back.

I think this due to some change in conda and the way that environment variables are parsed. It's a particular problem for PRs from external forks, where the tags aren't always present. I had a similar issue for BioSimSpace and needed to use the following logic in the recipe to fix things:

```
package:
  name: {{ name }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'PR') }}

source:
  git_url: BSS_REMOTE
  git_tag: BSS_BRANCH

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
```

According to the docs (and issue threads I found) it shouldn't be needed, but seemed to be the only thing that worked for me. I was meant to mention it to you (since my original code was based on your template), but apparently forgot. Ironically, I first noticed the issue with an external PR from @fjclark to the BioSimSpace repo.

Cheers.

**Comment by chryswoods** [comment]
Thanks @lohedges - I've updated the recipe in `devel` and have pulled the changes in here. Hopefully the build will work :-)

If it does, I will review and accept the PR, and will then backport to `main` via the open PR for 2023.3.1.

**Pull request merged**
