### PR TITLE
Feature add atoms positional restraints

### PR DESCRIPTION
**Pull request by mb2055**
This allows for the use of positional restraints on atoms that are consistent with the NPT ensemble. 

This replaces the now deprecated `setupRestraints` with `setupPositionalRestraints`
# Is this pull request to fix a bug, or to introduce new functionality?

A mixture, it replaces the old restraints with new ones consistent with the NPT ensemble through the use of dummy atoms.

## If this is to fix a bug...

This pull request fixes issue #59

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

## If this introduces new functionality...

Changes proposed in this pull request:

The flag `use_restraints` takes as input a dictionary of paired atom numbers in the form `{anchor:atom}` where `anchor` is a dummy atom with fixed cartesian coordinates. These dummy atoms are then bound to their respective real atom via a harmonic restraint, acting to fix it in place without causing issues with the MonteCarloBarostat.

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have added a test for any new functionality in this pull request: [n]
* I confirm that I have added documentation (e.g. a new tutorial page or detailed guide) for any new functionality in this pull request: [n]
* I confirm that I have permission to release this code under the GPL3 license: [y]

## Suggested reviewers:
@chryswoods, @lohedges

## Any additional context of information?

(you can also attach files by dragging & dropping)

### CODE REVIEW

**Comment by lohedges** [comment]
Just to say that this PR reverts the triclinic rounding fix in order to allow the test input to work. I'm working on fixing that elsewhere so we can merge into this branch if I figure something out. This shouldn't be merged into `devel` until we come up for a suitable workaround for that, otherwise it will break other functionality, e.g. replica-exchange with AMBER.

**Comment by lohedges** [comment]
Thanks, @mb2055. I should be able to look at this tomorrow.

**Comment by lohedges** [comment]
Just to say that the only reason that the build failed was that we forgot to skip the triclinic test now that the rounding fix has been removed. This can be resolved by adding the `@pytest.mark.xfail` decorator to the tests in [this](https://github.com/OpenBioSim/sire/blob/devel/tests/vol/test_triclinic.py) file.

**Review by chryswoods — APPROVED** [review]
These changes look good to me. We will re-run the CI once we have merged and updated the `feature_trajectory_save` PR (just to minimise CI and stack things up). Assuming all is ok, and @lohedges is happy with the Triclinic fix, then I am happy to merge.

**Review by chryswoods — APPROVED** [review]
All good - I’ll merge now :-)

**Pull request merged**
