### PR TITLE
Feature Merge

### PR DESCRIPTION
**Pull request by chryswoods**
This pull request is the first in a series which will add full perturbation / free energy support to the OpenMM contexts created by sire.

This PR introduces:

* A `LambdaSchedule` class that can be used to set up a schedule of how lambda will control different levers to change forcefield parameters.

* A `LambdaLever` class in SireOpenMM that actually changes the parameters in an OpenMM context based on the levers that are controlled via the `LambdaSchedule`

* Support for changing parameters in the OpenMM context. I have sub-classed the Python openmm.Context class to add extra functions, e.g. `set_lambda`, `set_schedule` etc. These make it easy to control the perturbation and change the context to represent the molecules in different lambda states.

This is all tested via `tests/convert/test_openmm_lambda.py`.

I am submitting this PR now so that it can be built on in the somd2 project.

There will be subsequent PRs that add in support for soft-core potentials, custom restraints that can be controlled by a `LambdaSchedule` / `LambdaLever`, and that will support creating / breaking bonds.

These subsequent PRs will bring in tutorials that will show how this new functionality can be used.

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have added a test for any new functionality in this pull request: [y]
* I confirm that I have added documentation (e.g. a new tutorial page or detailed guide) for any new functionality in this pull request: [n] - will do in subsequent PRs
* I confirm that I have added a changelog entry to the changelog (we will add a link to this PR as part of the review): [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

## Suggested reviewers:
@lohedges, @mb2055

### CODE REVIEW

**Comment by lohedges** [comment]
Thanks for this. Hopefully I'll be able to go through with @mb2055 later using your example to illustrate the API.

I've just tried setting the number of threads for the CPU platform using the helper function that you added but am seeing the following error:

```python
In [1]: import sire as sr

In [2]: mols = sr.stream.load("merged_molecule.s3")

In [3]: omm = sr.convert.to(mols, "openmm", map={"platform": "CPU"})

In [4]: omm.set_platform_property("Threads", 2)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/legacy/Convert/_sommcontex │
│ t.py:119 in set_platform_property                                                                │
│                                                                                                  │
│   116 │   │                                                                                      │
│   117 │   │   from ._SireOpenMM import _openmm_set_context_platform_property                     │
│   118 │   │                                                                                      │
│ ❱ 119 │   │   _openmm_set_context_platform_property(self, key, value)                            │
│   120 │                                                                                          │
│   121 │   def get_atom_index(self):                                                              │
│   122 │   │   """                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ArgumentError: Python argument types in
    sire.legacy.Convert._SireOpenMM._openmm_set_context_platform_property(SOMMContext, str, int)
did not match C++ signature:
    _openmm_set_context_platform_property(OpenMM::Context {lvalue} context, QString key, QString value)
```

Looking at the help, the API docs say...

```python
In [5]: help(omm.set_platform_property)
Help on method set_platform_property in module sire.legacy.Convert._sommcontext:

set_platform_property(key, value) method of sire.legacy.Convert._sommcontext.SOMMContext instance
    Set the value of the platform property 'key' to 'value'
```

...so it looks like I'm calling it properly. From the exception, it appears to be the call to the underlying OpenMM function that's the issue, i.e. it's not happy using the derived `SOMMContext` as the first argument.

Also, it appears that the value is documented as an `int`. Can it accept other things, such as a string? For example, we might want to specify a GPU `DeviceIndex` using something like `"0,1"`, which isn't expressible as an `int`.

**Comment by lohedges** [comment]
Actually, this was my fault, it should actually be passed as a string, not int. (I guess string is the most flexible, so the API docs for our wrapper should probably specify this.) In this case I get:

```python
In [5]: omm.set_platform_property("Threads", "2")
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/legacy/Convert/_sommcontex │
│ t.py:119 in set_platform_property                                                                │
│                                                                                                  │
│   116 │   │                                                                                      │
│   117 │   │   from ._SireOpenMM import _openmm_set_context_platform_property                     │
│   118 │   │                                                                                      │
│ ❱ 119 │   │   _openmm_set_context_platform_property(self, key, value)                            │
│   120 │                                                                                          │
│   121 │   def get_atom_index(self):                                                              │
│   122 │   │   """                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UserWarning: setPropertyValue: Illegal property name
```

This is the name of the property for CPU threads according to the OpenMM docs, so I'm not sure why it is failing. (Maybe the docs are out of date.) Indeed, if I give it an invalid property for the CPU platform then it tells me to use `Threads`!

```python
In [6]: omm.set_platform_property("threads", "2")
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/legacy/Convert/_sommcontex │
│ t.py:111 in set_platform_property                                                                │
│                                                                                                  │
│   108 │   │   if key not in keys:                                                                │
│   109 │   │   │   keys = ", ".join(keys)                                                         │
│   110 │   │   │                                                                                  │
│ ❱ 111 │   │   │   raise KeyError(                                                                │
│   112 │   │   │   │   f"There is no platform property called {key} in the "                      │
│   113 │   │   │   │   f"platform {platform.getName()}. Available properties "                    │
│   114 │   │   │   │   f"are [ {keys} ]"                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'There is no platform property called threads in the platform CPU. Available properties are [ Threads, DeterministicForces ]'
```

**Comment by chryswoods** [comment]
The function accepts a string, not an int. I'll add in some code to stringify it, but `omm.set_platform_property("Threads", "2")` should work (at least from the sire side)

The challenge is that OpenMM doesn't accept this, giving an error for me of

```
UserWarning: setPropertyValue: Illegal property name
```

I don't think this is changeable after creating the context (as I think other platform properties look like they are not changeable).

I can set the value correctly when the context is created, e.g.

```
>>> omm = sr.convert.to(mols, "openmm", map={"platform": "CPU", "threads": "5"})
>>> omm.get_platform_properties()
{'Threads': '5', 'DeterministicForces': 'false'}
```

(note that sire calls this `threads` not `Threads`, as I've tried to make the options pythonic in their naming for the sire/openmm interface)

**Comment by chryswoods** [comment]
You beat me to it ;-)

The message telling you to use a valid property name is generated by sire. This checks your passed property name against the list of property names reported by OpenMM, and raises an exception if it doesn't exist.

https://github.com/OpenBioSim/sire/blob/82701472c582d61a66fb798f004976949152857b/wrapper/Convert/SireOpenMM/_sommcontext.py#L108C7-L108C7

**Comment by lohedges** [comment]
Thanks, I was guessing that certain platform properties must be immutable. Since there is no `updatePlatform` method for a context, it will need to be set on creation, as you have shown. Thanks for exposing `threads` as a map option, we'll just use that :+1:

**Comment by chryswoods** [comment]
Here's the code that sets the platform property when the context is created:

https://github.com/OpenBioSim/sire/blob/82701472c582d61a66fb798f004976949152857b/wrapper/Convert/__init__.py#L304

**Comment by chryswoods** [comment]
I've just committed the code to stringify the option to `set_platform_property` and also added docs about the `threads` option to the OpenMM table of properties. These are "ci skipped" to save the CI.

**Comment by lohedges** [comment]
Perfect, many thanks. We'll have a play around this afternoon.

**Review by lohedges — APPROVED** [review]
All good. I really like the API.

**Comment by chryswoods** [comment]
The LambdaLever will be even better in the next PR ;-)

image

**Comment by lohedges** [comment]
Nice! Lambda lever, or magic wand 😉

**Pull request merged**
