### PR TITLE
Fix issue #130

### LINKED ISSUE #130: [BUG] perturbable_constraint validation doesn't check for underscores
Unlike for the `constraint` option, the validation of `perturbable_constraint` doesn't allow underscores, e.g. https://github.com/OpenBioSim/sire/blob/4a1025e8de9b5fb97c2670fa1de68b6bbf3c9d9f/wrapper/Convert/SireOpenMM/openmmmolecule.cpp#L86-L162

This option is now parsed via `sire.options.PerturbableConstraint`, which will sanitize all input to use underscores. As such, the creation of a dynamics object will fail for _any_ perturbable constraint other than `"none"` or `"auto"`.

### PR DESCRIPTION
**Pull request by lohedges**
This PR closes #130 by allowing the `perturbable_constraint` dynamics option to contain hyphens.

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have added a changelog entry to the changelog (we will add a link to this PR as part of the review): [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

## Suggested reviewers:
@chryswoods

### CODE REVIEW

**Review by chryswoods — APPROVED** [review]
Looks good. I think this highlights that the way I did this for constraint was error prone. I think it should be that there is a replace("-", "_") after the simplify, so that we can match any mix of hyphens or underscores.

**Comment by lohedges** [comment]
You do sanitize in the Python layer, i.e. everything gets converted to underscores. Are there situations where the C++ is being called directly?

**Comment by chryswoods** [comment]
Not currently, but it is better to be safe than sorry. There would be an edge case where someone sets this as a map parameter that bypasses the sanitation.

**Review by chryswoods — APPROVED** [review]
All good

**Pull request merged**
