### PR TITLE
Fixed analyse_freenrg...

### PR DESCRIPTION
**Pull request by chryswoods**
so that it uses `k_boltz.value()` and so that it can cope with `value°unit` temperatures as well as `value unit` temperatures.

The diff is bigger as the script has also been autoformatted using black.

The main fix is changing

```
temp = line.split()[3]
unit = line.split()[4]
```

into

```
temp = line.split()[3]

try:
    unit = line.split()[4]
except Exception:
    # this was a °C or °K (not that °K is correct!)
    temp, unit = temp.split("°")
```

The other change is having kelvin print out as `value K` rather `value°K` - it is not correct to use the degree sign for kelvin (my mistake)

# Is this pull request to fix a bug, or to introduce new functionality?

Fix a bug

This pull request fixes issue #6 

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

## Suggested reviewers:
@lohedges

## Any additional context of information?

(you can also attach files by dragging & dropping)

### CODE REVIEW

**Review by lohedges — APPROVED** [review]
Looks good to me.

Going forward it would be good to know who is still using `analyse_freenrg` (presumably Cresset). For BioSimSpace, we will be moving over to `alchemlyb` so that we can perform consistent analysis across engines and will deprecate the native analysis tools (`analyse_freenrg` and `gmx bar`) at this point. From then on their will likely be less users of this script, so it would be good to have some tests to ensure that it still works for those who do rely on it.

**Comment by jmichel80** [comment]
I think we will likely still support analyse_freenrg as a native sire app as long as somd is still used. My group members still use analyse_freenrg as the alchemlyb support is not ready yet. In general having a native implementation as a fall back is useful to ensure correctness of the alchemlyb implementation.

**Comment by lohedges** [comment]
Thanks, that's good to know. I do plan on leaving the fallback implementations in BioSimSpace so that it can work if/whenever `alchemlyb` isn't available, or the user doesn't want it in their environment for whatever reason. It would just be good to have a simple test (even just to see if it runs and produces output) in order to catch breakages due to any further Sire API changes going forward. (So we fix it during development, not retroactively.)

**Comment by chryswoods** [comment]
I am planning on creating a regression test in `sire_bigtests` based on the simfiles from Mark. This should give us some level of protection.

analyse_freenrg has two sides to it; there is the side used by Julien for MBAR analysis of somd runs, and there is the side built into sire that is used to analyse free energies from, e.g. waterswap et al. This uses the FEP, TI and BAR objects from SireAnalysis (https://github.com/OpenBioSim/sire/tree/devel/corelib/src/libs/SireAnalysis) to calculate free energies. I think we will always keep both the MBAR and other sides of analyse_freenrg in sire, as (aside from this breakage) they are relatively feature-full, robust and aren't too much to support.

**Pull request merged**
