### PR TITLE
Fix RDKit null molecule issue (58)

### PR DESCRIPTION
**Pull request by chryswoods**
Added a `must_sanitize` option that forces full sanitization of molecules generated

from smiles strings, and raises an exception if they fail to generate. This is set as default True.

If this is False, then sanitization is run manually, skipping any stages that fail.

Added a unit test to check this, plus added an addition to the documentation explaining the new mode.

## If this is to fix a bug...

This pull request fixes issue #58

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

## Suggested reviewers:
@lohedges

## Any additional context of information?

We are only a month away from the next major release. Do you think we are close enough that we can hold this for `2023.3.0` and not back-port to `2023.2.X`?

### CODE REVIEW

**Comment by lohedges** [comment]
Yes, I'm happy to delay if you think a full fix is fiddly. In the first instance the main thing is just you catch the error so we don't end up with an empty molecule in BioSimSpace during parameterisation. If it's easier, for now I could just catch this at my end.

**Comment by chryswoods** [comment]
This is a full fix - it was more me being lazy and trying to skip the back-port ;-)

I can back-port it if you think we will make another patch release before 2023.3.0.

**Comment by chryswoods** [comment]
I've just synchronised this with `devel`, and cancelled the CI as this PR is included in `feature_trajectory_save`.

**Comment by chryswoods** [comment]
Closing as this is automatically included in `feature_shared_properties`

**Pull request closed without merging**
