### PR TITLE
Fix issue #215

### LINKED ISSUE #215: [BUG] IFBOX pointer not set correctly for triclinic boxes
### Describe the bug:
When saving a solvated system to an Amber prm7 file, the IFBOX flag in the %FLAG POINTERS section is always set to 1, regardless of the box type used.
According to the Amber [Parameter-Topology file appendix](https://ambermd.org/prmtop.pdf) :

> IFBOX Flag indicating whether a periodic box is present. Values can be 0 (no box), 1 (orthorhombic box) or 2 (truncated octahedron)

### To Reproduce:
Build a truncated octahedron water box, save amber prm7 and rst7 file.
In prm7 file:

> Line 9:        0       0       0       0       0       0       0       1      X       0
1 is IFBOX value
X the number of atoms in the largest residue

At the end of the rst7 file:
>length length length 109.4711785  70.5287288  70.5287617

Run the simulation using the Amber engine. In the `mdout` file, a line in the RESOURCE USE section:

> BOX TYPE: RECTILINEAR

If check the wrapped trajectory, the box looks like this:
image

### Expected behavior:
1. prm7 file IFBOX flag set to 2
2. At the end of the rst7 file:
>length length length 109.4712190 109.4712190 109.4712190

*** The box angle must be set to 109.4712190 for Amber to recognize it correctly (Otherwise will have this in mdout file''Error: ifbox=2 in prmtop but angles are not correct''). Seems simply changing the angle in the rst7 file will cause the simulation to fail.

3. In mdout file:

> BOX TYPE: TRUNCATED OCTAHEDRON

4. If check the wrapped trajectory, the box should looks like truncated octahedron box:
image

### Input files:
The zip contains three folders:
from_bss: This folder contains the system built by BSS. Also a short NPT eq results.
modified: In this folder, the prm7 file has been modified to change the IFBOX flag to 2, and the rst7 file has been modified to match amber required angles. Also failed simulation results.
from_amber: This folder contains a similar-sized system in truncated octahedron water box built by Amber TLEaP with short NPT eq results.
[test.zip](https://github.com/user-attachments/files/16363534/test.zip)

 - OS:Linux (unbuntu 24.4.0)
 - Version of Python: 3.12.3
 - Version of BioSimSpace: dev
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: yes

### Additional context:
The IFBOX flag in the prm7 file is related to three other flags: SOLVENT POINTERS, ATOMS PER MOLECULE, and BOX DIMENSIONS.
However, it appears that as long as IFBOX is greater than 0, the data for the first two flags (SOLVENT POINTERS and ATOMS PER MOLECULE) will not be affected. The BOX DIMENSIONS flag will be affected, but it is deprecated as amber simulation now uses the box dimensions specified in the last line of the rst7 file.

### LINKED ISSUE #217: Migrate rdkit-dev to librdkit-dev
Hi, this is a friendly notification that the `rdkit-dev` conda-forge package has been replaced by `librdkit-dev` as of https://github.com/conda-forge/rdkit-feedstock/pull/158; please update your dependencies.

@lohedges thanks for inspiration to do this via github code search :)

### PR DESCRIPTION
**Pull request by lohedges**
This PR closes #215 by setting the `IFBOX` pointer to 3 for triclinic spaces. The value of 2 is reserved for a truncated octahedron. I'm not sure if we should add logic to detect this, or whether the use of 3 should suffice for everything. I'll test and report back if there are any issues.

Note that I've killed this superses #214, so I've killed the CI for that PR.

This also closes #217 by switching to the `librdkit-dev` package as a replacement for the now deprecated `rdkit-dev`.

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have added a changelog entry to the changelog (we will add a link to this PR as part of the review): [y/n]
* I confirm that I have permission to release this code under the GPL3 license: [y]

## Suggested reviewers:
@chryswoods

### CODE REVIEW

**Comment by lohedges** [comment]
It looks like the same version was installed for both the build _and_ tests (dev not for the tests):

```
    rdkit:                                2024.03.5-py312h7b4b7d0_1  conda-forge
    rdkit-dev:                            2024.03.5-ha4b6fd6_0       conda-forge
```

However, when building the wrappers it states:

```
-- Found RDKit library files at $PREFIX/lib/libRDKitGraphMol.so;$PREFIX/lib/libRDKitRDGeneral.so;$PREFIX/lib/libRDKitSmilesParse.so;$PREFIX/lib/libRDKitRDGeometryLib.so;$PREFIX/lib/libRDKitDistGeomHelpers.so;$PREFIX/lib/libRDKitForceField.so;$PREFIX/lib/libRDKitForceFieldHelpers.so;$PREFIX/lib/libRDKitSubstructMatch.so
-- Could NOT find RDKit (missing: RDKIT_INCLUDE_DIR) 
```

So, it looks like Sire doesn't work with this version of RDKit. Will install locally to try to work out what the problem is. Locally I have:

```
rdkit                     2024.03.4       py312h93d94ad_0    conda-forge
rdkit-dev                 2024.03.4            hcaeca22_0    conda-forge
```

**Comment by lohedges** [comment]
As per #217, `rdkit-dev` has been deprecated in favour of `librdkit-dev`. I've updated our requirements accordingly, which now means that we only have `librdkit-dev` as a _host_ requirement and a runtime dependency on an appropriate `rdkit` version. (Nothing related is in build.) I know see the following in the CI logs so I'm hoping things are fixed:

```
-- Found RDKit library files at $PREFIX/lib/libRDKitGraphMol.dylib;$PREFIX/lib/libRDKitRDGeneral.dylib;$PREFIX/lib/libRDKitSmilesParse.dylib;$PREFIX/lib/libRDKitRDGeometryLib.dylib;$PREFIX/lib/libRDKitDistGeomHelpers.dylib;$PREFIX/lib/libRDKitForceField.dylib;$PREFIX/lib/libRDKitForceFieldHelpers.dylib;$PREFIX/lib/libRDKitSubstructMatch.dylib
-- Found RDKit: $PREFIX/include/rdkit
```

**Comment by lohedges** [comment]
Nope, no `gemmi` errors for the last merge to `devel`, so this is new too.

**Comment by lohedges** [comment]
The version has not changed since yesterday (0.6.6) when it was detected during a previous CI run for this PR, so I'm not sure why it's not working. It certainly doesn't depend on RDKit.

**Comment by lohedges** [comment]
It seems like this fix won't work for SOMD1 since the old `amber.cpp` code makes some invalid assumptions about the value when it's set to 3:

```
    if (pointers[IFBOX] == 1)
    {
        /** Rectangular box, dimensions read from the crd file */
        Vector dimensions(crd_box[0], crd_box[1], crd_box[2]);

        // qDebug() << "We have a periodic box of dimensions"
        //          << crdBox[0] << crdBox[1] << crdBox[2];

        // PeriodicBox.
        if (crd_box[3] == 90.0 && crd_box[4] == 90.0 && crd_box[5] == 90.0)
        {
            spce = PeriodicBox(dimensions);
        }
        // TriclinicBox.
        else
        {
            spce = TriclinicBox(dimensions.x(), dimensions.y(), dimensions.z(), crd_box[3] * degrees,
                                crd_box[4] * degrees, crd_box[5] * degrees);
        }
        // spce = PeriodicBox( Vector ( crdBox[0], crdBox[1], crdBox[2] ) ).asA<Space>() ;
        // qDebug() << " periodic box " << spce.toString() ;
    }
    else if (pointers[IFBOX] == 2)
    {
        /** Truncated Octahedral box*/
        throw SireError::incompatible_error(QObject::tr("Sire does not yet support a truncated octahedral box"),
                                            CODELOC);
    }
    else
    {
        /** Default is a non periodic system */
        spce = Cartesian();
    }
```

The second clause will need to be set to `2 or 3` to catch truncated octahedron and general triclinic spaces.

**Comment by lohedges** [comment]
Hmm, weirdly later in the CI output I see:

```
Found gemmi version 0.6.6
```

So perhaps everything is actually okay?

**Comment by lohedges** [comment]
And `rdkit` was definitely installed for both the build and test:

`build:`:
```
2024-07-25T13:10:58.5407636Z     librdkit:                      2024.03.5-h4c5bbc8_1           conda-forge
2024-07-25T13:10:58.5408828Z     librdkit-dev:                  2024.03.5-h36c15f3_1           conda-forge
2024-07-25T13:16:33.7974170Z     rdkit:                         2024.03.5-py312h9d9823f_1      conda-forge
```

`test`:
```
2024-07-25T15:07:44.9229795Z     rdkit:                     2024.03.5-py312h9d9823f_1     conda-forge
```

The versions should clearly be compatible.

**Comment by lohedges** [comment]
Looking at the previous logs (where Windows worked) it seems that RDKit wasn't found during the build, so maybe the tests passed because they were actually skipped somehow.

**Comment by lohedges** [comment]
The Boresch errors are unrelated to the RDKit changes and appear to be caused by and IO error loading the fixtures for the tests. Hopefully those will be fixed by a simple re-run.

**Comment by lohedges** [comment]
Yes, the latest run solved the Boresch issues. Now we just have the RDKit issues on Windows:

```
2024-07-25T16:01:55.4991029Z FAILED tests/convert/test_rdkit.py::test_rdkit[C1CCCCC1] - TypeError: No to_python (by-value) converter found for C++ type: class boost::shared_ptr<class RDKit::ROMol>
2024-07-25T16:01:55.4992681Z FAILED tests/convert/test_rdkit.py::test_rdkit[C] - TypeError: No to_python (by-value) converter found for C++ type: class boost::shared_ptr<class RDKit::ROMol>
2024-07-25T16:01:55.4994274Z FAILED tests/convert/test_rdkit.py::test_rdkit[OCC(O)C(O)C(O)C(O)CO] - TypeError: No to_python (by-value) converter found for C++ type: class boost::shared_ptr<class RDKit::ROMol>
2024-07-25T16:01:55.4995861Z FAILED tests/convert/test_rdkit.py::test_rdkit[C[C@H](N)C(=O)O] - TypeError: No to_python (by-value) converter found for C++ type: class boost::shared_ptr<class RDKit::ROMol>
2024-07-25T16:01:55.4997426Z FAILED tests/convert/test_rdkit.py::test_rdkit[C[C@@H](N)C(=O)O] - TypeError: No to_python (by-value) converter found for C++ type: class boost::shared_ptr<class RDKit::ROMol>
2024-07-25T16:01:55.4998942Z FAILED tests/convert/test_rdkit.py::test_chirality - TypeError: No to_python (by-value) converter found for C++ type: class boost::shared_ptr<class RDKit::ROMol>
2024-07-25T16:01:55.5000435Z FAILED tests/convert/test_rdkit.py::test_hybridization - TypeError: No to_python (by-value) converter found for C++ type: class boost::shared_ptr<class RDKit::ROMol>
2024-07-25T16:01:55.5001943Z FAILED tests/convert/test_rdkit.py::test_hybridization2 - TypeError: No to_python (by-value) converter found for C++ type: class boost::shared_ptr<class RDKit::ROMol>
2024-07-25T16:01:55.5003474Z FAILED tests/convert/test_rdkit.py::test_rdkit_returns_null - TypeError: No to_python (by-value) converter found for C++ type: class boost::shared_ptr<class RDKit::ROMol>
2024-07-25T16:01:55.5005504Z FAILED tests/convert/test_rdkit.py::test_rdkit_infer_bonds - ImportError: You need to install rdkit to be able to generate smiles strings Do this by typing, e.g. 'conda install -c conda-forge rdkit' and then restarting Python and running this script/note>
2024-07-25T16:01:55.5007502Z FAILED tests/convert/test_rdkit.py::test_rdkit_preserve_info - TypeError: No to_python (by-value) converter found for C++ type: class boost::shared_ptr<class RDKit::ROMol>
2024-07-25T16:01:55.5009012Z FAILED tests/convert/test_smarts.py::test_smarts - TypeError: No to_python (by-value) converter found for C++ type: class boost::shared_ptr<class RDKit::ROMol>
```

As mentioned above, I'm not sure we had actually be previously compiling the RDKit support on Windows, so this _could_ be a longstanding issue that we've only just discovered. Not sure how to debug this without access to a Windows box or VM.

**Comment by chryswoods** [comment]
RDKit support did work on Windows, so it is a regression to lose it. I will look to debug next week.

**Comment by lohedges** [comment]
Thanks, I thought that was the case but recall it being a pain to get it working.

**Review by chryswoods — APPROVED** [review]

**Pull request merged**
