### PR TITLE
Fix re-occurence of issue #49

### PR DESCRIPTION
**Pull request by lohedges**
This PR fixes the re-occurence of issue #49 reported in #59. By changing the direction of the rounding bias we achieve stable angles _and_ a reduction that OpenMM is happy with. It is also possible to use a _smaller_ bias (smaller than the accuracy of the coordinates, angles, and box dimensions in the input files) which makes the reduction more precise. Another consequence is that our reduction now matches the default box angles suggested by GROMACS [here](https://manual.gromacs.org/current/reference-manual/algorithms/periodic-boundary-conditions.html). (Although the previous ones were a completely equivalent space.)

I've tested NPT simulations with each engine that BIoSimSpace supports and the box angles are stable when getting back a system at all points along the trajectory. I've also added a test to make sure that OpenMM remains happy with the reduction we apply to the standard triclinic space used by Cresset.

Fingers crossed this does the job :crossed_fingers: 

* I confirm that I have merged the latest version of `devel` into this branch before issuing this pull request (e.g. by running `git pull origin devel`): [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

## Suggested reviewers:
@chryswoods

### CODE REVIEW

**Review by chryswoods — APPROVED** [review]
All looks good. Hopefully this will work.

I've updated it to the latest changes in devel. Feel free to merge when you are happy :-)

**Comment by chryswoods** [comment]
I'll merge this - I am about to submit the units PR which will roll up everything else. Merging your PR will make it easier to submit mine :-)

**Comment by lohedges** [comment]
Great. We'll just have to make sure that `devel` is merged into @mb2055`s branch before merging so that my fix overwrites the temporary workaround.

**Comment by chryswoods** [comment]
I'll merge in @mb2055's branch after merging in the (monster) PR I am about to submit ;-). This will merge everything together.

**Pull request merged**
