### PR TITLE
Backport fix from PR #123

### PR DESCRIPTION
**Pull request by lohedges**
This PR backports the fix from #123 into `main`.

* I confirm that I have merged the latest version of `main` into this branch before issuing this pull request (e.g. by running `git pull origin main`): [y]
* I confirm that I have permission to release this code under the GPL3 license: [y]

### CODE REVIEW

**Comment by lohedges** [comment]
Not sure if I also need to add the entry to the CHANGELOG? This is done on `devel` under the 2023.5.0 section. Perhaps you look at fixes from that section when creating a patch release and add them to the respective 2023.4.X section.

**Comment by chryswoods** [comment]
Could you create a `2023.4.2` section in the changelog and add it to there? I then compare the devel changelog to the one in main when I do the next major release, and will remove anything that is duplicated from the previous patch release.

**Comment by lohedges** [comment]
Yes, no problem. I just wasn't completely sure of the system since you could end up adding a section for a patch release that never happens. I guess it all gets sorted out at release time anyway, so it's good to have something to cross reference.

**Comment by lohedges** [comment]
Done :+1:

**Pull request merged**
